version: 2.1

jobs:
  screenshot:
    executor: node/default
    working_directory: ~/screenshot-ci
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build next server
          command: npm run build
      - run:
          name: Run next server
          command: npm run start
          background: true
      - run:
          name: Run tests
          command: npm test
      - store_artifacts:
          name: Saving puppeteer screenshots
          path: ~/screenshot-ci/screenshots/__snapshots__
          destination: /screenshot-ci

orbs:
  node: circleci/node@3.0.0
workflows:
  main-pipeline:
    jobs:
      - screenshot
